version: "3"
services:
  api:
    image: muriloscapim/api-ts
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: dubc/mongodb-4.0
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no